In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the data
df = pd.read_csv(r"C:\Users\glotzie\Downloads\archive\electric_vehicles_spec_2025.csv.csv")

df.head()

,brand,model,top_speed_kmh,battery_capacity_kWh,battery_type,number_of_cells,torque_nm,efficiency_wh_per_km,range_km,acceleration_0_100_s,...,towing_capacity_kg,cargo_volume_l,seats,drivetrain,segment,length_mm,width_mm,height_mm,car_body_type,source_url
0,Abarth,500e Convertible,155,37.8,Lithium-ion,192.0,235.0,156,225,7.0,...,0.0,185,4,FWD,B - Compact,3673,1683,1518,Hatchback,https://ev-database.org/car/1904/Abarth-500e-C...
1,Abarth,500e Hatchback,155,37.8,Lithium-ion,192.0,235.0,149,225,7.0,...,0.0,185,4,FWD,B - Compact,3673,1683,1518,Hatchback,https://ev-database.org/car/1903/Abarth-500e-H...
2,Abarth,600e Scorpionissima,200,50.8,Lithium-ion,102.0,345.0,158,280,5.9,...,0.0,360,5,FWD,JB - Compact,4187,1779,1557,SUV,https://ev-database.org/car/3057/Abarth-600e-S...
3,Abarth,600e Turismo,200,50.8,Lithium-ion,102.0,345.0,158,280,6.2,...,0.0,360,5,FWD,JB - Compact,4187,1779,1557,SUV,https://ev-database.org/car/3056/Abarth-600e-T...
4,Aiways,U5,150,60.0,Lithium-ion,NaN,310.0,156,315,7.5,...,NaN,496,5,FWD,JC - Medium,4680,1865,1700,SUV,https://ev-database.org/car/1678/Aiways-U5

Each row represents one electric vehicle model.
Each column describes one specification of the vehicle.

In [2]:
df.shape

(478, 22)

Expected Output (478, 22) There are

478 Electric Vehicles

22 Features

In [3]:
df.columns

Index(['brand', 'model', 'top_speed_kmh', 'battery_capacity_kWh',
       'battery_type', 'number_of_cells', 'torque_nm', 'efficiency_wh_per_km',
       'range_km', 'acceleration_0_100_s', 'fast_charging_power_kw_dc',
       'fast_charge_port', 'towing_capacity_kg', 'cargo_volume_l', 'seats',
       'drivetrain', 'segment', 'length_mm', 'width_mm', 'height_mm',
       'car_body_type', 'source_url'],
      dtype='str')

In [4]:
df.info()

numerical_columns = df.select_dtypes(include=np.number).columns
categorical_columns = df.select_dtypes(exclude=np.number).columns
print(numerical_columns)
print(categorical_columns)

<class 'pandas.DataFrame'>
RangeIndex: 478 entries, 0 to 477
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   brand                      478 non-null    str
 1   model                      477 non-null    str
 2   top_speed_kmh              478 non-null    int64
 3   battery_capacity_kWh       478 non-null    float64
 4   battery_type               478 non-null    str
 5   number_of_cells            276 non-null    float64
 6   torque_nm                  471 non-null    float64
 7   efficiency_wh_per_km       478 non-null    int64
 8   range_km                   478 non-null    int64
 9   acceleration_0_100_s       478 non-null    float64
 10  fast_charging_power_kw_dc  477 non-null    float64
 11  fast_charge_port           477 non-null    str
 12  towing_capacity_kg         452 non-null    float64
 13  cargo_volume_l             477 non-null    str
 14  seats                      478 non-null    int64
 15  drivetrain                 478 non-null    str
 16  segment                    478 non-null    str
 17  length_mm                  478 non-null    int64
 18  width_mm                   478 non-null    int64
 19  height_mm                  478 non-null    int64
 20  car_body_type              478 non-null    str
 21  source_url                 478 non-null    str
dtypes: float64(6), int64(7), str(9)
memory usage: 82.3 KB
Index(['top_speed_kmh', 'battery_capacity_kWh', 'number_of_cells', 'torque_nm',
       'efficiency_wh_per_km', 'range_km', 'acceleration_0_100_s',
       'fast_charging_power_kw_dc', 'towing_capacity_kg', 'seats', 'length_mm',
       'width_mm', 'height_mm'],
      dtype='str')
Index(['brand', 'model', 'battery_type', 'fast_charge_port', 'cargo_volume_l',
       'drivetrain', 'segment', 'car_body_type', 'source_url'],
      dtype='str')

In [5]:
df.isnull().sum()
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": df.isnull().mean()*100
})

missing

                           Missing Values  Percentage
brand                                   0    0.000000
model                                   1    0.209205
top_speed_kmh                           0    0.000000
battery_capacity_kWh                    0    0.000000
battery_type                            0    0.000000
number_of_cells                       202   42.259414
torque_nm                               7    1.464435
efficiency_wh_per_km                    0    0.000000
range_km                                0    0.000000
acceleration_0_100_s                    0    0.000000
fast_charging_power_kw_dc               1    0.209205
fast_charge_port                        1    0.209205
towing_capacity_kg                     26    5.439331
cargo_volume_l                          1    0.209205
seats                                   0    0.000000
drivetrain                              0    0.000000
segment                                 0    0.000000
length_mm                               0    0.000000
width_mm                                0    0.000000
height_mm                               0    0.000000
car_body_type                           0    0.000000
source_url                              0    0.000000